### ISSUE TITLE
add dynare path to Matlab

### ISSUE THREAD

**Issue by NarekOhanyan** [gboehl/pynare#1]
**The issue:**

Python with pynare package fails to run a .mod file with the following error
_MatlabExecutionError: Undefined function 'dynare' for input arguments of type 'char'._

It seems the Dynare path is not added to Matlab before running the model.

**To reproduce:**

import pynare
Mod = pynare.pynare(modpath='./somemodelfile.mod')

**Possible solution:**

I could resolve the issue by adding the following line to the file core.py
...
with PipeOutput(self.logfile, sys.stdout):
&nbsp;&nbsp;&nbsp;&nbsp;_self.eng.eval('addpath("/usr/lib/dynare/matlab/")', nargout=0)_
&nbsp;&nbsp;&nbsp;&nbsp;self.eng.eval('dynare '+self.modname, nargout=0)
...

**Comment by gboehl** [comment]
Hi, sorry that I am just seeing this now. Would you want to send a pull request with your fix? That would be great!

**Comment by NarekOhanyan** [comment]
Hi, sure, I would be happy to make PR. However, this fix would work for a Linux-based OS, whereas dynare would be installed in different paths on Mac and Windows. Hence a complete solution would require a more general approach.

**Comment by gboehl** [comment]
From my perspective this should be fine. I would assume that this is primarily interesting for linux users after all. In any case, you could wrap your fix in a
```
if platform == "linux" or platform == "linux2":
    # your fix
```

**Comment by gboehl** [comment]
But wouldn't the better solution be to permanently add dynare to your matlab path? Also, the path of dynare is not the same across linux distributions (at least not for Arch vs. Ubuntu).

**Comment by NarekOhanyan** [comment]
You're right, the installation path may be different even across different linux distributions, so probably adding something about it in the documentation is a good idea. But I think instead of asking users to add dynare path to Matlab permanently (which may not be straightforward for them to do), we may ask users to provide the dynare path when they import the library. It can look something like this:
```python
from pynare import pynare, set_dynare_path
set_dynare_path('/usr/lib/dynare/matlab/')
mod = pynare('modfile.mod')
```

**Comment by gboehl** [comment]
This sounds like the best idea!

Would you be willing to prepare a PR?

I'm happy to add it to the documentation then.



On 09.10.22 10:57:50, Narek Ohanyan wrote:
> You're right, the installation path may be different even across different linux distributions, so probably adding something about it in the documentation is a good idea. But I think instead of asking users to add dynare path to Matlab permanently (which may not be straightforward for them to do), we may ask users to provide the dynare path when they import the library. It can look something like this:
> ```python
> from pynare import pynare, set_dynare_path
> set_dynare_path('/usr/lib/dynare/matlab/')
> mod = pynare('modfile.mod')
> ```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/gboehl/pynare/issues/1#issuecomment-1272595966
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

-- 
Dr. Gregor Boehl
Postdoctoral researcher
University of Bonn
Principal investigator DFG Project 441540692
Mail: 	***@***.***
Web: 	https://gregorboehl.com

**Comment by NarekOhanyan** [comment]
Sure, I will take care of it!
